config/routes.rb
Cateccorp::Application.routes.draw do
  
   match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :attendees

  resources :conferences

   root :to => 'welcome#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	has_and_belongs_to_many :conferences
  attr_accessible :apoderado, :career, :cellphone, :ci, :city, :direction, :directionapoderado, :email, :first, :health, :last, :last2, :level, :other, :parentesco, :telephone, :telephoneapoderado, :zone, :conference_ids, :detail
end

app/models/conference.rb
class Conference < ActiveRecord::Base
	has_and_belongs_to_many :attendees
  attr_accessible :category, :date, :name, :obligatory, :speaker, :time, :conference_ids
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :detail, :name, :oauth_expires_at, :oauth_token, :provider, :uid, :email, :fist_name, :last_name, :location, :verified, :urls, :image, :admin

  def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.first_name = auth.info.first_name
    user.last_name = auth.info.last_name
    user.image = auth.info.image
    user.urls = auth.info.urls
    user.location = auth.info.location
    user.verified = auth.info.verified
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # before_filter :authenticate_user!, except: [:index, :show]
 protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController


  # GET /attendees
  # GET /attendees.json
  def index
    @attendees = Attendee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.json
  def create
    @attendee = Attendee.new(params[:attendee])
      

      



    respond_to do |format|
      if @attendee.save
        AttendeeMailer.signup_confirmation(@attendee).deliver

        format.html { redirect_to @attendee, notice: 'Attendee was successfully created.' }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to @attendee, notice: 'Attendee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(params[:conference])

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendees/_form.html.erb
<%= form_for @attendee, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Nombre:", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Apellido Paterno", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Apellido Materno", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Carrera", :class => 'control-label', :for => 'inputIcon' %>
    <div class="controls">
      <%= f.text_field :career, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Institución", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :level, options_for_select([["Elija una Institución", "no eligio"], ["UCATEC", "ucatec"], ["CATEC", "catec"]]) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Email", :class => 'control-label' %>
    <div class="controls">
      <div class="input-prepend">
      <span class="add-on"><i class="icon-envelope"></i></span>
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "CI", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ci, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Ciudad", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :city, options_for_select([["Elija una Ciudad", "no eligio"], ["Cochabamba", "Cochabamba"], ["Santa Cruz", "Santa Cruz"], ["Oruro", "Oruro"], ["Tarija", "Tarija"]]) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Direccion", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direction, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Zona", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Telefono", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telephone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Celular", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cellphone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Otro Numero", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :other, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label "Apoderado", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :apoderado, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Parentesco", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :parentesco, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Telefono de Apoderado", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telephoneapoderado, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Direccion de Apoderado", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :directionapoderado, :class => 'text_field' %>
    </div>
  </div>

<div class="control-group">
    <%= f.label "Comentarios", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :health, :class => 'text_area' %>
    </div>
  </div>

<div class = "hero-unit">
<h2>Seminarios</h2>

<% for conference in Conference.find(:all) %>
        <div>
                <%= check_box_tag "attendee[conference_ids][]", conference.id, @attendee.conferences.include?(conference)  %>
                <%= conference.name %>
                
        </div>
   <% end %>
</div>


  <div class="form-actions">
    <%= f.submit "Registrarme!", :class => 'btn btn-primary' %>
<% if current_user %>
  <% if current_user.admin %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                attendees_path, :class => 'btn' %>
                <% end -%>
                <% end -%>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attendees/index.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1>Asistentes</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first) %></th>
      <th><%= model_class.human_attribute_name(:last) %></th>
      <th><%= model_class.human_attribute_name(:last2) %></th>
      <th><%= model_class.human_attribute_name(:career) %></th>
      <th><%= model_class.human_attribute_name(:level) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:ci) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:direction) %></th>
      <th><%= model_class.human_attribute_name(:zone) %></th>
      <th><%= model_class.human_attribute_name(:telephone) %></th>
      <th><%= model_class.human_attribute_name(:cellphone) %></th>
      <th><%= model_class.human_attribute_name(:other) %></th>
      <th><%= model_class.human_attribute_name(:health) %></th>
      <th><%= model_class.human_attribute_name(:apoderado) %></th>
      <th><%= model_class.human_attribute_name(:parentesco) %></th>
      <th><%= model_class.human_attribute_name(:telephoneapoderado) %></th>
      <th><%= model_class.human_attribute_name(:directionapoderado) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td><%= link_to attendee.id, attendee_path(attendee) %></td>
        <td><%= attendee.first %></td>
        <td><%= attendee.last %></td>
        <td><%= attendee.last2 %></td>
        <td><%= attendee.career %></td>
        <td><%= attendee.level %></td>
        <td><%= attendee.email %></td>
        <td><%= attendee.ci %></td>
        <td><%= attendee.city %></td>
        <td><%= attendee.direction %></td>
        <td><%= attendee.zone %></td>
        <td><%= attendee.telephone %></td>
        <td><%= attendee.cellphone %></td>
        <td><%= attendee.other %></td>
        <td><%= attendee.health %></td>
        <td><%= attendee.apoderado %></td>
        <td><%= attendee.parentesco %></td>
        <td><%= attendee.telephoneapoderado %></td>
        <td><%= attendee.directionapoderado %></td>
        <td><%=l attendee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_attendee_path(attendee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      attendee_path(attendee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_attendee_path,
            :class => 'btn btn-primary' %>

app/views/attendees/new.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <div class = "row-fluid">
  
  <div class = "span8"><h1>Nuevo Registro</h1></div><div class = "span4"> <div class ="btn "><%= link_to "Ver los precios", :controller => "welcome", :action => "prices"  %></div></div>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/attendees/show.html.erb
<%- model_class = Attendee -%>
<div class="page-header">
  <h1>Detalle del Registro</h1>
</div>
<dl class="dl-horizontal">
  <dt><strong>Nombre:</strong></dt>
  <dd><%= @attendee.first %></dd>
  <dt><strong>Apellido Paterno:</strong></dt>
  <dd><%= @attendee.last %></dd>
  <dt><strong>Apellido Materno:</strong></dt>
  <dd><%= @attendee.last2 %></dd>
  <dt><strong>Carrera:</strong></dt>
  <dd><%= @attendee.career %></dd>
  <dt><strong>Nivel:</strong></dt>
  <dd><%= @attendee.level %></dd>
  <dt><strong>Tu Email:</strong></dt>
  <dd><%= @attendee.email %></dd>
  <dt><strong>Carnet de Identidad:</strong></dt>
  <dd><%= @attendee.ci %></dd>
  <dt><strong>Ciudad:</strong></dt>
  <dd><%= @attendee.city %></dd>
  <dt><strong>Dirección:</strong></dt>
  <dd><%= @attendee.direction %></dd>
  <dt><strong>Zona:</strong></dt>
  <dd><%= @attendee.zone %></dd>
  <dt><strong>Telefono:</strong></dt>
  <dd><%= @attendee.telephone %></dd>
  <dt><strong>Celular:</strong></dt>
  <dd><%= @attendee.cellphone %></dd>
  <dt><strong>Otro numero:</strong></dt>
  <dd><%= @attendee.other %></dd>
  <dt><strong>Comentarios:</strong></dt>
  <dd><%= @attendee.health %></dd>
  <dt><strong>Nombre del Apoderado:</strong></dt>
  <dd><%= @attendee.apoderado %></dd>
  <dt><strong>Parentesco del Apoderado:</strong></dt>
  <dd><%= @attendee.parentesco %></dd>
  <dt><strong>Telefono del apoderado:</strong></dt>
  <dd><%= @attendee.telephoneapoderado %></dd>
  <dt><strong>Dirección del apoderado:</strong></dt>
  <dd><%= @attendee.directionapoderado %></dd>
</dl>

<% if current_user %>
  <% if current_user.admin %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              attendees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_attendee_path(@attendee), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              attendee_path(@attendee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% end -%>
<% end -%>

app/views/conferences/_form.html.erb
<%= form_for @conference, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label "Nombre", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Hora", :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :time, :class => 'time_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Dia", :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Categoria", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Obligatorio?", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :obligatory, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Expositor", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :speaker, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                conferences_path, :class => 'btn' %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<%- model_class = Conference -%>
<div class="page-header">

  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conferences/index.html.erb
<% if current_user %>
  <% if current_user.admin %> 
    <%- model_class = Conference -%>
    <div class="page-header">
      <h1>Conferencias</h1>
    </div>
    <!-- ya pues -->
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:time) %></th>
          <th><%= model_class.human_attribute_name(:date) %></th>
          <th><%= model_class.human_attribute_name(:category) %></th>
          <th><%= model_class.human_attribute_name(:obligatory) %></th>
          <th><%= model_class.human_attribute_name(:speaker) %></th>
          <th><%= model_class.human_attribute_name(:created_at) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @conferences.each do |conference| %>
          <tr>
            <td><%= link_to conference.id, conference_path(conference) %></td>
            <td><%= conference.name %></td>
            <td><%= conference.time.strftime('%H:%M') %></td>
            <td><%= conference.date.to_formatted_s(:long) %></td>
            <td><%= conference.category %></td>
            <td><%= conference.obligatory %></td>
            <td><%= conference.speaker %></td>
            <td><%=l conference.created_at %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_conference_path(conference), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          conference_path(conference),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_conference_path,
                :class => 'btn btn-primary' %>
  <% end -%>
<% end -%>

 <!-- aqui empieza lo bonito -->




<%- model_class = Conference -%>
<div class="page-header">
  <div class = "row-fluid">
  
  <div class = "span8"><h1>Conferencias</h1></div><div class = "span4"> <div class = "btn"> <%= image_tag("pdf2.png") %> <a href="http://www.workig.com/EncuentroTarija17.pdf">Descargar Programa Completo en PDF</a> </div></div>
  </div>
</div>
<table class="table table-striped">
 <div class ="row-fluid"> 
    <div class = "btn btn-primary disabled span4">Titulo de la conferencia</div>
    <div class = "btn btn-info disabled span2">Hora</div>
    <div class = "btn btn-warning disabled span2">Fecha</div>
    <div class = "btn btn-danger disabled span2">Categoria</div>
    <div class = "btn btn-success disabled span2">Expositor</div>

</div>
  <tbody>
    <% @conferences.each do |conference| %>
      

    <div class ="row-fluid">
        <div class = "btn span12" style= "padding:30px; margin-top:20px; margin-bottom:20px;" >
          <div class ="row-fluid">
            <div class = "btn btn-primary disabled span12" style = "margin-bottom:15px"><%= conference.name %></div>
            <div class ="row-fluid">
            <div class = "btn btn-info disabled span2"><%= conference.time.strftime('%H:%M') %></div>
            <div class = "btn btn-warning disabled span3"><%= conference.date.to_formatted_s(:long) %></div>
            <div class = "btn btn-danger disabled span3"><%= conference.category %></div>
            <div class = "btn btn-success disabled span4"><%= conference.speaker %></div>
          </div>
         </div>
        </div>
    </div>
      


          <% end %>
  </tbody>
</table>

app/views/conferences/new.html.erb
<%- model_class = Conference -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conferences/show.html.erb
<%- model_class = Conference -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @conference.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @conference.time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @conference.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @conference.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obligatory) %>:</strong></dt>
  <dd><%= @conference.obligatory %></dd>
  <dt><strong><%= model_class.human_attribute_name(:speaker) %>:</strong></dt>
  <dd><%= @conference.speaker %></dd>
</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              conferences_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_conference_path(@conference), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              conference_path(@conference),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/welcome/admin.html.erb
<div class = "hero-unit">
			
                                <% if current_user %>
                   <div class = "span6">
                    Iniciaste sesion como <strong><%= current_user.name %></strong>!
                    <%= link_to "Cerrar sesion", signout_path, id: "sign_out" %>
                  </div>
                  <% else %>
                  <div class = "span6">
                           <div class ="btn "><%= link_to "Inicia sesion con tu Facebook", "/auth/facebook", id: "sign_in" %> </div>
                  </div>
                  <% end %>
             
                   <% if current_user %>
                   <% else %>


                    <h5> <%= link_to "Registro Sin Facebook", :controller => "attendees", :action => "new" %> </h5>
            
                <% end -%>
      

      <% if current_user%>
            <div class ="btn btn-primary"><%= link_to "Continuar", :controller => "attendees", :action => "new" %> </div>
      <% else %>
      <% end -%>

</div>

app/views/welcome/registration.html.erb
<div class = "hero-unit">
			
                            
<h3>Ya estas con un pie en el encuentro 2013!</h3>

                    <div class ="btn ">  <%= link_to "Registrarme para participar del encuentro!", :controller => "attendees", :action => "new" %>  </div>
            
   
</div>